sudo: false
language: python
python:
    - "3.4"
addons:
    postgresql: "9.3"
install:
    - pip3 install -r requirements_afm.txt
    - pip3 install -r requirements_agent.txt
before_script:
    - psql -U postgres -c "DROP DATABASE IF EXISTS slamon;"
    - psql -U postgres -c "DROP DATABASE IF EXISTS slamon_tests;"
    - psql -U postgres -c "DROP USER IF EXISTS afm;"
    - psql -U postgres -c "CREATE DATABASE slamon;"
    - psql -U postgres -c "CREATE DATABASE slamon_tests;"
    - psql -U postgres -c "CREATE USER afm WITH PASSWORD 'changeme';"
    - psql -U postgres -c "GRANT ALL ON DATABASE slamon TO afm;"
    - psql -U postgres -c "GRANT ALL ON DATABASE slamon_tests TO afm;"
script:
    - nosetests
